### ISSUE TITLE
Make Limit Plot Interpolation Function Configurable

### ISSUE THREAD

**Issue by lawrenceleejr** [tvami/HSCPbackgroundPred#1]
Notes for @taylorsussmane. From @tvami:

> 
> here is the relevant dir
> https://github.com/tvami/HSCPbackgroundPred/tree/master/DataStudies/limitPlotScripts
> I run 
> ```
> cd DataStudies/2DAlpha_1Dfrom2DNoExtrapol_200GeV
> cp ../limitPlotScripts/* .
> python set_limit.py -s signals_ppStau.txt -m ppStauCut200GeV
> ```
> where the `ppStauCut100GeV` is really just a label

@tvami can post some example inputs here later.

It looks like the interpolation happens here https://github.com/tvami/HSCPbackgroundPred/blob/437ea22d6b6d64dbe2777af28ed3e8fd03d8aa38/DataStudies/limitPlotScripts/header.py#L1372-L1391 where there's a linear assumption. @taylorsussmane your tasks would be to make this configurable so that it can do an exponential interpolation to find the intercept. Then we can compare the two where the function is being used here: https://github.com/tvami/HSCPbackgroundPred/blob/437ea22d6b6d64dbe2777af28ed3e8fd03d8aa38/DataStudies/limitPlotScripts/set_limit.py#L321

**Comment by tvami** [comment]
ok @taylorsussmane I uploaded the inputs, under `DataStudies/2DAlpha_1Dfrom2DNoExtrapol_200GeV` you can run
```
cd DataStudies/2DAlpha_1Dfrom2DNoExtrapol_200GeV
cp ../limitPlotScripts/* .
python set_limit.py -s signals_ppStau.txt -m ppStauCut200GeV
```

**Comment by tvami** [comment]
@taylorsussmane do you have any news on this?

**Comment by tvami** [comment]
@lawrenceleejr do you know if there was any progress done on this?

**Comment by lawrenceleejr** [comment]
Hey @tvami -- sorry about the silence. Yes @taylorsussmane started doing this, but has been busy with other things. I'll get in touch and work with her to get this implemented.

**Comment by lawrenceleejr** [comment]
The PR above closes this ticket. To document some numbers, running over the gluino grid, the original code gave an intersection of:

```
Expected mass limit: 2.077 +0.092 -0.114 TeV
Expected xsection limit at excluded mass: 0.000758 +0.000302 -0.000602 pb
```

Using the new linear interpolation which doesn't do the stepping and only uses the information in the graphs themselves gives:
```
Expected mass limit: 2.076 +0.092 -0.113 TeV
Expected xsection limit at excluded mass: 0.00076 +0.000302 -0.000605 pb
```

The exponential interpolation finds:
```
Expected mass limit: 2.058 +0.096 -0.112 TeV
Expected xsection limit at excluded mass: 0.000748 +0.000296 -0.000601 pb
```

Looking at the plot that comes out, it looks like this 2.058 TeV is a better representation of the plot's intersection than 2.077 TeV.

<img width="1614" alt="Screen Shot 2023-03-21 at 10 17 29 AM" src="https://user-images.githubusercontent.com/7438278/226638483-6480116c-67a9-4a57-82d3-4aa7a0da11ce.png">

So @tvami once you merge the PR, this task will be done!
